name = "Vireframe"
description = "Gutenberg theme powered by Bulma, Vue.js"
license = "MIT"
homepage = "https://github.com/lettenj61/vireframe/"

# The minimum version of Gutenberg required
min_version = "0.1"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Gutenberg
[extra.vireframe]
bulmaswatch = { href = "https://unpkg.com/bulmaswatch/materia/bulmaswatch.min.css" }

[extra.vireframe.vue]
  src = "https://unpkg.com/vue"
  plugins = [
    "https://unpkg.com/vuex"
  ]

# The theme author info: you!
[author]
name = "lettenj61"
homepage = "https://github.com/lettenj61/
