name = "Vireframe"
description = "Gutenberg theme powered by Bulma, Vue.js"
license = "MIT"
homepage = "https://github.com/lettenj61/vireframe/"

# The minimum version of Gutenberg required
min_version = "0.1"

# Bulma configurations
[extra]
  # Link to bulma stylesheet itself
  vireframe_vulma = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.0/css/bulma.min.css"
  # Link to icon fonts used with bulma
  vireframe_icons = "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  # Source URL for Vue.js script
  vireframe_vue = "https://unpkg.com/vue"
  # Vue plugins to load into rendered HTML headers
  # Note that they will not installed automatically, you must set up them in your app script.
  vireframe_vue_plugins = [
    "https://unpkg.com/vuex"
  ]

# The theme author info: you!
[author]
name = "lettenj61"
homepage = "https://github.com/lettenj61/"
